**ライブラリの読み込み**

In [1]:
import os
import re
import polars as pl

**設定値の定義**

In [2]:
occto_path = r"/workspace/src/stg/data_lake/occto"

**データの読み込み**

In [3]:
df_occto = pl.scan_csv(os.path.join(occto_path,"*.csv")).collect()
df_occto.head()

shape: (5, 56)
┌────────────┬────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ 発電所コー ┆ エリア ┆ 発電所名   ┆ ユニット  ┆ … ┆ 23:30[kWh ┆ 24:00[kWh ┆ 日量[kWh] ┆ 更新日時  │
│ ド         ┆ ---    ┆ ---        ┆ 名        ┆   ┆ ]         ┆ ]         ┆ ---       ┆ ---       │
│ ---        ┆ str    ┆ str        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ i64       ┆ str       │
│ str        ┆        ┆            ┆ str       ┆   ┆ i64       ┆ i64       ┆           ┆           │
╞════════════╪════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 10001      ┆ 北海道 ┆ 泊発電所   ┆ １号機    ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 2024/11/2 │
│            ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆ 7         │
│            ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆ 15:31:05  │
│ 10001      ┆ 北海道 ┆ 泊発電所   ┆ ２号機    ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 2024/11/2 │
│            ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆ 7         │
│            ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆ 15:31:05  │
│ 10001      ┆ 北海道 ┆ 泊発電所   ┆ ３号機    ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 2024/11/2 │
│            ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆ 7         │
│            ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆ 15:31:05  │
│ 13017      ┆ 北海道 ┆ 京極発電所 ┆ １号機    ┆ … ┆ 0         ┆ 0         ┆ 399960    ┆ 2024/11/2 │
│            ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆ 7         │
│            ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆ 15:31:05  │
│ 13017      ┆ 北海道 ┆ 京極発電所 ┆ ２号機    ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 2024/11/2 │
│            ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆ 7         │
│            ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆ 15:31:05  │
└────────────┴────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [4]:
df_occto.schema

Schema([('発電所コード', String),
        ('エリア', String),
        ('発電所名', String),
        ('ユニット名', String),
        ('発電方式・燃種', String),
        ('対象日', String),
        ('00:30[kWh]', Int64),
        ('01:00[kWh]', Int64),
        ('01:30[kWh]', Int64),
        ('02:00[kWh]', Int64),
        ('02:30[kWh]', Int64),
        ('03:00[kWh]', Int64),
        ('03:30[kWh]', Int64),
        ('04:00[kWh]', Int64),
        ('04:30[kWh]', Int64),
        ('05:00[kWh]', Int64),
        ('05:30[kWh]', Int64),
        ('06:00[kWh]', Int64),
        ('06:30[kWh]', Int64),
        ('07:00[kWh]', Int64),
        ('07:30[kWh]', Int64),
        ('08:00[kWh]', Int64),
        ('08:30[kWh]', Int64),
        ('09:00[kWh]', Int64),
        ('09:30[kWh]', Int64),
        ('10:00[kWh]', Int64),
        ('10:30[kWh]', Int64),
        ('11:00[kWh]', Int64),
        ('11:30[kWh]', Int64),
        ('12:00[kWh]', Int64),
        ('12:30[kWh]', Int64),
        ('13:00[kWh]', Int64),
        ('13:30[kWh]', Int64),
        ('14:00[kWh]', Int64),
        ('14:30[kWh]', Int64),
        ('15:00[kWh]', Int64),
        ('15:30[kWh]', Int64),
        ('16:00[kWh]', Int64),
        ('16:30[kWh]', Int64),
        ('17:00[kWh]', Int64),
        ('17:30[kWh]', Int64),
        ('18:00[kWh]', Int64),
        ('18:30[kWh]', Int64),
        ('19:00[kWh]', Int64),
        ('19:30[kWh]', Int64),
        ('20:00[kWh]', Int64),
        ('20:30[kWh]', Int64),
        ('21:00[kWh]', Int64),
        ('21:30[kWh]', Int64),
        ('22:00[kWh]', Int64),
        ('22:30[kWh]', Int64),
        ('23:00[kWh]', Int64),
        ('23:30[kWh]', Int64),
        ('24:00[kWh]', Int64),
        ('日量[kWh]', Int64),
        ('更新日時', String)])

In [5]:
df_occto.describe()

shape: (9, 57)
┌────────────┬────────────┬────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ 発電所コー ┆ エリア ┆ 発電所名  ┆ … ┆ 23:30[kWh ┆ 24:00[kWh ┆ 日量[kWh] ┆ 更新日時  │
│ ---        ┆ ド         ┆ ---    ┆ ---       ┆   ┆ ]         ┆ ]         ┆ ---       ┆ ---       │
│ str        ┆ ---        ┆ str    ┆ str       ┆   ┆ ---       ┆ ---       ┆ f64       ┆ str       │
│            ┆ str        ┆        ┆           ┆   ┆ f64       ┆ f64       ┆           ┆           │
╞════════════╪════════════╪════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 177750     ┆ 177750 ┆ 177750    ┆ … ┆ 173378.0  ┆ 173377.0  ┆ 173230.0  ┆ 177750    │
│ null_count ┆ 0          ┆ 0      ┆ 0         ┆ … ┆ 4372.0    ┆ 4373.0    ┆ 4520.0    ┆ 0         │
│ mean       ┆ null       ┆ null   ┆ null      ┆ … ┆ 81108.766 ┆ 78378.508 ┆ 3.7987e6  ┆ null      │
│            ┆            ┆        ┆           ┆   ┆ 591       ┆ 014       ┆           ┆           │
│ std        ┆ null       ┆ null   ┆ null      ┆ … ┆ 128328.92 ┆ 126781.53 ┆ 5.8240e6  ┆ null      │
│            ┆            ┆        ┆           ┆   ┆ 8391      ┆ 8369      ┆           ┆           │
│ min        ┆ 00101      ┆ 中国   ┆ ひびき灘  ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 2024/11/2 │
│            ┆            ┆        ┆ 石炭・バ  ┆   ┆           ┆           ┆           ┆ 7         │
│            ┆            ┆        ┆ イオマス  ┆   ┆           ┆           ┆           ┆ 15:31:05  │
│            ┆            ┆        ┆ 発電所    ┆   ┆           ┆           ┆           ┆           │
│ 25%        ┆ null       ┆ null   ┆ null      ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ null      │
│ 50%        ┆ null       ┆ null   ┆ null      ┆ … ┆ 0.0       ┆ 0.0       ┆ 795000.0  ┆ null      │
│ 75%        ┆ null       ┆ null   ┆ null      ┆ … ┆ 120000.0  ┆ 114000.0  ┆ 5.336e6   ┆ null      │
│ max        ┆ OA32915H40 ┆ 関西   ┆ ＪＦＥス  ┆ … ┆ 589269.0  ┆ 1.103e6   ┆ 2.8288028 ┆ 2025/11/2 │
│            ┆            ┆        ┆ チール株  ┆   ┆           ┆           ┆ e7        ┆ 6         │
│            ┆            ┆        ┆ 式会社川  ┆   ┆           ┆           ┆           ┆ 15:30:06  │
│            ┆            ┆        ┆ 鉄千葉ク  ┆   ┆           ┆           ┆           ┆           │
│            ┆            ┆        ┆ リーンパ  ┆   ┆           ┆           ┆           ┆           │
│            ┆            ┆        ┆ ワーステ  ┆   ┆           ┆           ┆           ┆           │
│            ┆            ┆        ┆ ーション  ┆   ┆           ┆           ┆           ┆           │
└────────────┴────────────┴────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [6]:
df_occto.null_count()

shape: (1, 56)
┌────────────┬────────┬──────────┬────────────┬───┬────────────┬────────────┬───────────┬──────────┐
│ 発電所コー ┆ エリア ┆ 発電所名 ┆ ユニット名 ┆ … ┆ 23:30[kWh] ┆ 24:00[kWh] ┆ 日量[kWh] ┆ 更新日時 │
│ ド         ┆ ---    ┆ ---      ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---      │
│ ---        ┆ u32    ┆ u32      ┆ u32        ┆   ┆ u32        ┆ u32        ┆ u32       ┆ u32      │
│ u32        ┆        ┆          ┆            ┆   ┆            ┆            ┆           ┆          │
╞════════════╪════════╪══════════╪════════════╪═══╪════════════╪════════════╪═══════════╪══════════╡
│ 0          ┆ 0      ┆ 0        ┆ 366        ┆ … ┆ 4372       ┆ 4373       ┆ 4520      ┆ 0        │
└────────────┴────────┴──────────┴────────────┴───┴────────────┴────────────┴───────────┴──────────┘

In [7]:
cols = df_occto.columns
unpivot_cols = [col for col in cols if col not in ["発電所コード", "エリア", "発電所名", "ユニット名", "発電方式・燃種", "対象日", "更新日時"]]
print(unpivot_cols)

['00:30[kWh]', '01:00[kWh]', '01:30[kWh]', '02:00[kWh]', '02:30[kWh]', '03:00[kWh]', '03:30[kWh]', '04:00[kWh]', '04:30[kWh]', '05:00[kWh]', '05:30[kWh]', '06:00[kWh]', '06:30[kWh]', '07:00[kWh]', '07:30[kWh]', '08:00[kWh]', '08:30[kWh]', '09:00[kWh]', '09:30[kWh]', '10:00[kWh]', '10:30[kWh]', '11:00[kWh]', '11:30[kWh]', '12:00[kWh]', '12:30[kWh]', '13:00[kWh]', '13:30[kWh]', '14:00[kWh]', '14:30[kWh]', '15:00[kWh]', '15:30[kWh]', '16:00[kWh]', '16:30[kWh]', '17:00[kWh]', '17:30[kWh]', '18:00[kWh]', '18:30[kWh]', '19:00[kWh]', '19:30[kWh]', '20:00[kWh]', '20:30[kWh]', '21:00[kWh]', '21:30[kWh]', '22:00[kWh]', '22:30[kWh]', '23:00[kWh]', '23:30[kWh]', '24:00[kWh]', '日量[kWh]']

## データ加工

### 横持ち→縦持ち変換

In [8]:
df_occto_melted = df_occto.unpivot(index=["発電所コード", "エリア", "発電所名", "ユニット名", "発電方式・燃種", "対象日", "更新日時"], on = unpivot_cols, variable_name="時間帯", value_name="供給力[kWh]")
print(df_occto_melted.shape)
df_occto_melted.head()

(8709750, 9)

shape: (5, 9)
┌────────────┬────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ 発電所コー ┆ エリア ┆ 発電所名   ┆ ユニット  ┆ … ┆ 対象日    ┆ 更新日時  ┆ 時間帯    ┆ 供給力[kW │
│ ド         ┆ ---    ┆ ---        ┆ 名        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ h]        │
│ ---        ┆ str    ┆ str        ┆ ---       ┆   ┆ str       ┆ str       ┆ str       ┆ ---       │
│ str        ┆        ┆            ┆ str       ┆   ┆           ┆           ┆           ┆ i64       │
╞════════════╪════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 10001      ┆ 北海道 ┆ 泊発電所   ┆ １号機    ┆ … ┆ 2024/11/2 ┆ 2024/11/2 ┆ 00:30[kWh ┆ 0         │
│            ┆        ┆            ┆           ┆   ┆ 6         ┆ 7         ┆ ]         ┆           │
│            ┆        ┆            ┆           ┆   ┆           ┆ 15:31:05  ┆           ┆           │
│ 10001      ┆ 北海道 ┆ 泊発電所   ┆ ２号機    ┆ … ┆ 2024/11/2 ┆ 2024/11/2 ┆ 00:30[kWh ┆ 0         │
│            ┆        ┆            ┆           ┆   ┆ 6         ┆ 7         ┆ ]         ┆           │
│            ┆        ┆            ┆           ┆   ┆           ┆ 15:31:05  ┆           ┆           │
│ 10001      ┆ 北海道 ┆ 泊発電所   ┆ ３号機    ┆ … ┆ 2024/11/2 ┆ 2024/11/2 ┆ 00:30[kWh ┆ 0         │
│            ┆        ┆            ┆           ┆   ┆ 6         ┆ 7         ┆ ]         ┆           │
│            ┆        ┆            ┆           ┆   ┆           ┆ 15:31:05  ┆           ┆           │
│ 13017      ┆ 北海道 ┆ 京極発電所 ┆ １号機    ┆ … ┆ 2024/11/2 ┆ 2024/11/2 ┆ 00:30[kWh ┆ 10890     │
│            ┆        ┆            ┆           ┆   ┆ 6         ┆ 7         ┆ ]         ┆           │
│            ┆        ┆            ┆           ┆   ┆           ┆ 15:31:05  ┆           ┆           │
│ 13017      ┆ 北海道 ┆ 京極発電所 ┆ ２号機    ┆ … ┆ 2024/11/2 ┆ 2024/11/2 ┆ 00:30[kWh ┆ 0         │
│            ┆        ┆            ┆           ┆   ┆ 6         ┆ 7         ┆ ]         ┆           │
│            ┆        ┆            ┆           ┆   ┆           ┆ 15:31:05  ┆           ┆           │
└────────────┴────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

### 不要なデータの除外

In [9]:
df_occto_filtered = df_occto_melted.filter(pl.col("時間帯") != "日量[kWh]")
print(df_occto_filtered.shape)
df_occto_filtered.head()

(8532000, 9)

shape: (5, 9)
┌────────────┬────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ 発電所コー ┆ エリア ┆ 発電所名   ┆ ユニット  ┆ … ┆ 対象日    ┆ 更新日時  ┆ 時間帯    ┆ 供給力[kW │
│ ド         ┆ ---    ┆ ---        ┆ 名        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ h]        │
│ ---        ┆ str    ┆ str        ┆ ---       ┆   ┆ str       ┆ str       ┆ str       ┆ ---       │
│ str        ┆        ┆            ┆ str       ┆   ┆           ┆           ┆           ┆ i64       │
╞════════════╪════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 10001      ┆ 北海道 ┆ 泊発電所   ┆ １号機    ┆ … ┆ 2024/11/2 ┆ 2024/11/2 ┆ 00:30[kWh ┆ 0         │
│            ┆        ┆            ┆           ┆   ┆ 6         ┆ 7         ┆ ]         ┆           │
│            ┆        ┆            ┆           ┆   ┆           ┆ 15:31:05  ┆           ┆           │
│ 10001      ┆ 北海道 ┆ 泊発電所   ┆ ２号機    ┆ … ┆ 2024/11/2 ┆ 2024/11/2 ┆ 00:30[kWh ┆ 0         │
│            ┆        ┆            ┆           ┆   ┆ 6         ┆ 7         ┆ ]         ┆           │
│            ┆        ┆            ┆           ┆   ┆           ┆ 15:31:05  ┆           ┆           │
│ 10001      ┆ 北海道 ┆ 泊発電所   ┆ ３号機    ┆ … ┆ 2024/11/2 ┆ 2024/11/2 ┆ 00:30[kWh ┆ 0         │
│            ┆        ┆            ┆           ┆   ┆ 6         ┆ 7         ┆ ]         ┆           │
│            ┆        ┆            ┆           ┆   ┆           ┆ 15:31:05  ┆           ┆           │
│ 13017      ┆ 北海道 ┆ 京極発電所 ┆ １号機    ┆ … ┆ 2024/11/2 ┆ 2024/11/2 ┆ 00:30[kWh ┆ 10890     │
│            ┆        ┆            ┆           ┆   ┆ 6         ┆ 7         ┆ ]         ┆           │
│            ┆        ┆            ┆           ┆   ┆           ┆ 15:31:05  ┆           ┆           │
│ 13017      ┆ 北海道 ┆ 京極発電所 ┆ ２号機    ┆ … ┆ 2024/11/2 ┆ 2024/11/2 ┆ 00:30[kWh ┆ 0         │
│            ┆        ┆            ┆           ┆   ┆ 6         ┆ 7         ┆ ]         ┆           │
│            ┆        ┆            ┆           ┆   ┆           ┆ 15:31:05  ┆           ┆           │
└────────────┴────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

### 対象日時カラムの作成

In [10]:
df_occto_dt = df_occto_filtered.with_columns(
    pl.when(pl.col("時間帯").str.contains("24:00"))
    .then(
        # 24:00の場合、対象日に1日加算して00:00に変換する
        (
            pl.col("対象日").str.to_date(format="%Y/%m/%d") + pl.duration(days=1)
        ).cast(pl.Utf8) + pl.lit(" 00:00")
    )
    .otherwise(
        # 24:00が含まれない場合: 元の文字列 (対象日 + 時間帯) を使用
        pl.col('対象日') + pl.lit(' ') + pl.col('時間帯').str.replace(r'\"?\[kWh\]\"?', '').str.strip_chars()
    ).alias("対象日時_str")
).with_columns(
    # 日時文字列をdatetime型に変換する
    pl.col("対象日時_str").str.to_datetime(format="%Y/%m/%d %H:%M").alias("対象日時")
).drop(["時刻","対象日時_str","対象日"])

print(df_occto_dt.shape)
df_occto_dt.head()

InvalidOperationError: conversion from `str` to `datetime[μs]` failed in column '対象日時_str' for 177750 out of 8532000 values: ["2024-11-27 00:00", "2024-11-27 00:00", … "2024-11-27 00:00"]

You might want to try:
- setting `strict=False` to set values that cannot be converted to `null`
- using `str.strptime`, `str.to_date`, or `str.to_datetime` and providing a format string