# Electric forecast historical data scraping

## Import libraries

In [6]:
import os
import time
import requests
import zipfile
from io import StringIO, BytesIO
from bs4 import BeautifulSoup
from datetime import date,datetime
import polars as pl
import numpy as np

## Scrape historical data

### Tokyo

In [2]:
BASE_URL = "https://www.tepco.co.jp/forecast/html/images"
OUTPUT_PATH = r"/workspace/src/stg/data_lake/electric_forecast/tokyo"

#### Scrape raw csv files

In [4]:
for year in range(2016, 2023):
    file_name = f"juyo-{year}.csv"
    url = f"{BASE_URL}/{file_name}"
    response = requests.get(url)

    if response.status_code == 200:
        print(f"Processing data for year {year}")
        df = pl.read_csv(source=url, encoding="cp932", skip_rows=2)
        df.write_parquet(os.path.join(OUTPUT_PATH, f"juyo-{year}.parquet"))
        print(f"Saved parquet for year {year}")
    else:
        print(f"Failed to retrieve data for year {year}")
        continue

    time.sleep(np.random.uniform(1, 3))

Processing data for year 2016
Saved parquet for year 2016
Processing data for year 2017
Saved parquet for year 2017
Processing data for year 2018
Saved parquet for year 2018
Processing data for year 2019
Saved parquet for year 2019
Processing data for year 2020
Saved parquet for year 2020
Processing data for year 2021
Saved parquet for year 2021
Processing data for year 2022
Saved parquet for year 2022

In [5]:
tokyo_parquet = r"/workspace/src/stg/data_lake/electric_forecast/tokyo/juyo-2022.parquet"
df_tokyo_2022 = pl.read_parquet(tokyo_parquet)
df_tokyo_2022.head()

shape: (5, 3)
┌──────────┬──────┬────────────┐
│ DATE     ┆ TIME ┆ 実績(万kW) │
│ ---      ┆ ---  ┆ ---        │
│ str      ┆ str  ┆ i64        │
╞══════════╪══════╪════════════╡
│ 2022/1/1 ┆ 0:00 ┆ 3266       │
│ 2022/1/1 ┆ 1:00 ┆ 3062       │
│ 2022/1/1 ┆ 2:00 ┆ 2929       │
│ 2022/1/1 ┆ 3:00 ┆ 2828       │
│ 2022/1/1 ┆ 4:00 ┆ 2786       │
└──────────┴──────┴────────────┘

#### Scrape Zip files

In [ ]:
ZIP_PATH = r"/workspace/src/stg/data_lake/electric_forecast/tokyo/zip"
year_list = [i for i in range(2022,2026)]
month_list = [i for i in range(1,13)]
print(year_list,month_list)

[2022, 2023, 2024, 2025] [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [ ]:
#for year in year_list:
#for month in range(2,13):
zip_file_name = "202512_power_usage.zip"
zip_url = f"{BASE_URL}/{zip_file_name}"
response = requests.get(zip_url)

if response.status_code == 200:
    with open(os.path.join(ZIP_PATH, zip_file_name), 'wb') as f:
        f.write(response.content)
    print(f"Downloaded {zip_file_name}")
else:
    print(f"Failed to download {zip_file_name}")

    time.sleep(np.random.uniform(3, 6))

Downloaded 202502_power_usage.zip
Downloaded 202503_power_usage.zip
Downloaded 202504_power_usage.zip
Downloaded 202505_power_usage.zip
Downloaded 202506_power_usage.zip
Downloaded 202507_power_usage.zip
Downloaded 202508_power_usage.zip
Downloaded 202509_power_usage.zip
Downloaded 202510_power_usage.zip
Downloaded 202511_power_usage.zip
Downloaded 202512_power_usage.zip

### Hokkaido

In [16]:
HKD_PATH = r"/workspace/src/stg/data_lake/electric_forecast/hokkaido"
HKD_BASE_URL = "https://denkiyoho.hepco.co.jp/area/data/zip"
QUARTER = {
    1:"04-06",
    2:"07-09",
    3:"10-12",
    4:"01-03"
}
HKD_YEAR_LIST = [i for i in range(2020,2026)]

In [17]:
for year in HKD_YEAR_LIST:
    for quarter in QUARTER.values():
        zip_file_name = f"{year}{quarter}_hokkaido_denkiyohou.zip"
        zip_url = f"{HKD_BASE_URL}/{zip_file_name}"
        response = requests.get(zip_url)

        if response.status_code == 200:
            with open(os.path.join(HKD_PATH, zip_file_name), 'wb') as f:
                f.write(response.content)
            print(f"Downloaded {zip_file_name}")
        else:
            print(f"Failed to download {zip_file_name}")

            time.sleep(np.random.uniform(1, 5))

Downloaded 202004-06_hokkaido_denkiyohou.zip
Downloaded 202007-09_hokkaido_denkiyohou.zip
Downloaded 202010-12_hokkaido_denkiyohou.zip
Failed to download 202001-03_hokkaido_denkiyohou.zip
Downloaded 202104-06_hokkaido_denkiyohou.zip
Downloaded 202107-09_hokkaido_denkiyohou.zip
Downloaded 202110-12_hokkaido_denkiyohou.zip
Downloaded 202101-03_hokkaido_denkiyohou.zip
Downloaded 202204-06_hokkaido_denkiyohou.zip
Downloaded 202207-09_hokkaido_denkiyohou.zip
Downloaded 202210-12_hokkaido_denkiyohou.zip
Downloaded 202201-03_hokkaido_denkiyohou.zip
Downloaded 202304-06_hokkaido_denkiyohou.zip
Downloaded 202307-09_hokkaido_denkiyohou.zip
Downloaded 202310-12_hokkaido_denkiyohou.zip
Downloaded 202301-03_hokkaido_denkiyohou.zip
Downloaded 202404-06_hokkaido_denkiyohou.zip
Downloaded 202407-09_hokkaido_denkiyohou.zip
Downloaded 202410-12_hokkaido_denkiyohou.zip
Downloaded 202401-03_hokkaido_denkiyohou.zip
Downloaded 202504-06_hokkaido_denkiyohou.zip
Downloaded 202507-09_hokkaido_denkiyohou.zip
Downloaded 202510-12_hokkaido_denkiyohou.zip
Downloaded 202501-03_hokkaido_denkiyohou.zip

### Tohoku

In [19]:
THK_PATH = r"/workspace/src/stg/data_lake/electric_forecast/tohoku"
THK_BASE_URL = "https://setsuden.nw.tohoku-epco.co.jp/common/demand/"
THK_YEAR_LIST = [i for i in range(2016,2026)]

In [20]:
for year in THK_YEAR_LIST:
    file_name = f"juyo_{year}_tohoku.csv"
    url = f"{THK_BASE_URL}/{file_name}"
    response = requests.get(url)

    if response.status_code == 200:
        print(f"Processing data for year {year}")
        df = pl.read_csv(source=url, encoding="cp932", skip_rows=1)
        df.write_parquet(os.path.join(THK_PATH, f"juyo_{year}_tohoku.parquet"))
        print(f"Saved parquet for year {year}")
    else:
        print(f"Failed to retrieve data for year {year}")
        continue

    time.sleep(np.random.uniform(1, 5))

Processing data for year 2016
Saved parquet for year 2016
Processing data for year 2017
Saved parquet for year 2017
Processing data for year 2018
Saved parquet for year 2018
Processing data for year 2019
Saved parquet for year 2019
Processing data for year 2020
Saved parquet for year 2020
Processing data for year 2021
Saved parquet for year 2021
Processing data for year 2022
Saved parquet for year 2022
Processing data for year 2023
Saved parquet for year 2023
Processing data for year 2024
Saved parquet for year 2024
Processing data for year 2025
Saved parquet for year 2025

### Chubu

In [21]:
CHB_PATH = r"/workspace/src/stg/data_lake/electric_forecast/chubu/zip"
CHB_BASE_URL = "https://powergrid.chuden.co.jp/denki_yoho_content_data/download_csv/"
CHB_YEAR_LIST = [i for i in range(2019,2026)]
CHB_MONTH_LIST = [i for i in range(1,13)]

In [24]:
#201912_power_usage.zip
for year in CHB_YEAR_LIST:
    for month in CHB_MONTH_LIST:
        zip_file_name = f"{year}{str(month).zfill(2)}_power_usage.zip"
        zip_url = f"{CHB_BASE_URL}/{zip_file_name}"
        time.sleep(np.random.uniform(1, 5))
        response = requests.get(zip_url)
        if response.status_code == 200:
            with open(os.path.join(CHB_PATH, zip_file_name), 'wb') as f:
                f.write(response.content)
            print(f"Downloaded {zip_file_name}")
        else:
            print(f"Failed to download {zip_file_name}")

Failed to download 201901_power_usage.zip
Failed to download 201902_power_usage.zip
Failed to download 201903_power_usage.zip
Downloaded 201904_power_usage.zip
Downloaded 201905_power_usage.zip
Downloaded 201906_power_usage.zip
Downloaded 201907_power_usage.zip
Downloaded 201908_power_usage.zip
Downloaded 201909_power_usage.zip
Downloaded 201910_power_usage.zip
Downloaded 201911_power_usage.zip
Downloaded 201912_power_usage.zip
Downloaded 202001_power_usage.zip
Downloaded 202002_power_usage.zip
Downloaded 202003_power_usage.zip
Downloaded 202004_power_usage.zip
Downloaded 202005_power_usage.zip
Downloaded 202006_power_usage.zip
Downloaded 202007_power_usage.zip
Downloaded 202008_power_usage.zip
Downloaded 202009_power_usage.zip
Downloaded 202010_power_usage.zip
Downloaded 202011_power_usage.zip
Downloaded 202012_power_usage.zip
Downloaded 202101_power_usage.zip
Downloaded 202102_power_usage.zip
Downloaded 202103_power_usage.zip
Downloaded 202104_power_usage.zip
Downloaded 202105_power_usage.zip
Downloaded 202106_power_usage.zip
Downloaded 202107_power_usage.zip
Downloaded 202108_power_usage.zip
Downloaded 202109_power_usage.zip
Downloaded 202110_power_usage.zip
Downloaded 202111_power_usage.zip
Downloaded 202112_power_usage.zip
Downloaded 202201_power_usage.zip
Downloaded 202202_power_usage.zip
Downloaded 202203_power_usage.zip
Downloaded 202204_power_usage.zip
Downloaded 202205_power_usage.zip
Downloaded 202206_power_usage.zip
Downloaded 202207_power_usage.zip
Downloaded 202208_power_usage.zip
Downloaded 202209_power_usage.zip
Downloaded 202210_power_usage.zip
Downloaded 202211_power_usage.zip
Downloaded 202212_power_usage.zip
Downloaded 202301_power_usage.zip
Downloaded 202302_power_usage.zip
Downloaded 202303_power_usage.zip
Downloaded 202304_power_usage.zip
Downloaded 202305_power_usage.zip
Downloaded 202306_power_usage.zip
Downloaded 202307_power_usage.zip
Downloaded 202308_power_usage.zip
Downloaded 202309_power_usage.zip
Downloaded 202310_power_usage.zip
Downloaded 202311_power_usage.zip
Downloaded 202312_power_usage.zip
Downloaded 202401_power_usage.zip
Downloaded 202402_power_usage.zip
Downloaded 202403_power_usage.zip
Downloaded 202404_power_usage.zip
Downloaded 202405_power_usage.zip
Downloaded 202406_power_usage.zip
Downloaded 202407_power_usage.zip
Downloaded 202408_power_usage.zip
Downloaded 202409_power_usage.zip
Downloaded 202410_power_usage.zip
Downloaded 202411_power_usage.zip
Downloaded 202412_power_usage.zip
Downloaded 202501_power_usage.zip
Downloaded 202502_power_usage.zip
Downloaded 202503_power_usage.zip
Downloaded 202504_power_usage.zip
Downloaded 202505_power_usage.zip
Downloaded 202506_power_usage.zip
Downloaded 202507_power_usage.zip
Downloaded 202508_power_usage.zip
Downloaded 202509_power_usage.zip
Downloaded 202510_power_usage.zip
Downloaded 202511_power_usage.zip
Downloaded 202512_power_usage.zip

### Kansai

In [3]:
KNS_PATH = r"/workspace/src/stg/data_lake/electric_forecast/kansai"
KNS_BASE_URL = "https://www.kansai-td.co.jp/yamasou"
KNS_YEAR_LIST = [i for i in range(2016,2026)]
KNS_MONTH_LIST = [i for i in range(1,13)]

In [6]:
for year in KNS_YEAR_LIST:
    for month in KNS_MONTH_LIST:
        zip_file_name = f"{year}{str(month).zfill(2)}_jisseki.zip"
        zip_url = f"{KNS_BASE_URL}/{zip_file_name}"
        time.sleep(np.random.uniform(1, 5))
        response = requests.get(zip_url)
        if response.status_code == 200:
            with open(os.path.join(KNS_PATH, zip_file_name), 'wb') as f:
                f.write(response.content)
            print(f"Downloaded {zip_file_name}")
        else:
            print(f"Failed to download {zip_file_name}")

Failed to download 201601_jisseki.zip
Failed to download 201602_jisseki.zip
Failed to download 201603_jisseki.zip
Downloaded 201604_jisseki.zip
Downloaded 201605_jisseki.zip
Downloaded 201606_jisseki.zip
Downloaded 201607_jisseki.zip
Downloaded 201608_jisseki.zip
Downloaded 201609_jisseki.zip
Downloaded 201610_jisseki.zip
Downloaded 201611_jisseki.zip
Downloaded 201612_jisseki.zip
Downloaded 201701_jisseki.zip
Downloaded 201702_jisseki.zip
Downloaded 201703_jisseki.zip
Downloaded 201704_jisseki.zip
Downloaded 201705_jisseki.zip
Downloaded 201706_jisseki.zip
Downloaded 201707_jisseki.zip
Downloaded 201708_jisseki.zip
Downloaded 201709_jisseki.zip
Downloaded 201710_jisseki.zip
Downloaded 201711_jisseki.zip
Downloaded 201712_jisseki.zip
Downloaded 201801_jisseki.zip
Downloaded 201802_jisseki.zip
Downloaded 201803_jisseki.zip
Downloaded 201804_jisseki.zip
Downloaded 201805_jisseki.zip
Downloaded 201806_jisseki.zip
Downloaded 201807_jisseki.zip
Downloaded 201808_jisseki.zip
Downloaded 201809_jisseki.zip
Downloaded 201810_jisseki.zip
Downloaded 201811_jisseki.zip
Downloaded 201812_jisseki.zip
Downloaded 201901_jisseki.zip
Downloaded 201902_jisseki.zip
Downloaded 201903_jisseki.zip
Downloaded 201904_jisseki.zip
Downloaded 201905_jisseki.zip
Downloaded 201906_jisseki.zip
Downloaded 201907_jisseki.zip
Downloaded 201908_jisseki.zip
Downloaded 201909_jisseki.zip
Downloaded 201910_jisseki.zip
Downloaded 201911_jisseki.zip
Downloaded 201912_jisseki.zip
Downloaded 202001_jisseki.zip
Downloaded 202002_jisseki.zip
Downloaded 202003_jisseki.zip
Downloaded 202004_jisseki.zip
Downloaded 202005_jisseki.zip
Downloaded 202006_jisseki.zip
Downloaded 202007_jisseki.zip
Downloaded 202008_jisseki.zip
Downloaded 202009_jisseki.zip
Downloaded 202010_jisseki.zip
Downloaded 202011_jisseki.zip
Downloaded 202012_jisseki.zip
Downloaded 202101_jisseki.zip
Downloaded 202102_jisseki.zip
Downloaded 202103_jisseki.zip
Downloaded 202104_jisseki.zip
Downloaded 202105_jisseki.zip
Downloaded 202106_jisseki.zip
Downloaded 202107_jisseki.zip
Downloaded 202108_jisseki.zip
Downloaded 202109_jisseki.zip
Downloaded 202110_jisseki.zip
Downloaded 202111_jisseki.zip
Downloaded 202112_jisseki.zip
Downloaded 202201_jisseki.zip
Downloaded 202202_jisseki.zip
Downloaded 202203_jisseki.zip
Downloaded 202204_jisseki.zip
Downloaded 202205_jisseki.zip
Downloaded 202206_jisseki.zip
Downloaded 202207_jisseki.zip
Downloaded 202208_jisseki.zip
Downloaded 202209_jisseki.zip
Downloaded 202210_jisseki.zip
Downloaded 202211_jisseki.zip
Downloaded 202212_jisseki.zip
Downloaded 202301_jisseki.zip
Downloaded 202302_jisseki.zip
Downloaded 202303_jisseki.zip
Downloaded 202304_jisseki.zip
Downloaded 202305_jisseki.zip
Downloaded 202306_jisseki.zip
Downloaded 202307_jisseki.zip
Downloaded 202308_jisseki.zip
Downloaded 202309_jisseki.zip
Downloaded 202310_jisseki.zip
Downloaded 202311_jisseki.zip
Downloaded 202312_jisseki.zip
Downloaded 202401_jisseki.zip
Downloaded 202402_jisseki.zip
Downloaded 202403_jisseki.zip
Downloaded 202404_jisseki.zip
Downloaded 202405_jisseki.zip
Downloaded 202406_jisseki.zip
Downloaded 202407_jisseki.zip
Downloaded 202408_jisseki.zip
Downloaded 202409_jisseki.zip
Downloaded 202410_jisseki.zip
Downloaded 202411_jisseki.zip
Downloaded 202412_jisseki.zip
Downloaded 202501_jisseki.zip
Downloaded 202502_jisseki.zip
Downloaded 202503_jisseki.zip
Downloaded 202504_jisseki.zip
Downloaded 202505_jisseki.zip
Downloaded 202506_jisseki.zip
Downloaded 202507_jisseki.zip
Downloaded 202508_jisseki.zip
Downloaded 202509_jisseki.zip
Downloaded 202510_jisseki.zip
Downloaded 202511_jisseki.zip
Downloaded 202512_jisseki.zip

### Chugoku

In [10]:
CGK_PATH = r"/workspace/src/stg/data_lake/electric_forecast/chugoku"
CGK_URL = "https://www.energia.co.jp/nw/jukyuu/sys/"
CGK_YEAR_LIST = [i for i in range(2010,2026)]

In [11]:
for year in CGK_YEAR_LIST:
    file_name = f"juyo-{str(year)}.csv"
    url = f"{CGK_URL}/{file_name}"
    time.sleep(np.random.uniform(1, 5))
    response = requests.get(url)
    if response.status_code == 200:
        print(f"Processing data for year {year}")
        df = pl.read_csv(source=url, encoding="cp932", skip_rows=2)
        df.write_parquet(os.path.join(CGK_PATH, f"juyo-{year}.parquet"))
        print(f"Saved parquet for year {year}")
    else:
        print(f"Failed to retrieve data for year {year}")
        continue

Failed to retrieve data for year 2010
Failed to retrieve data for year 2011
Failed to retrieve data for year 2012
Failed to retrieve data for year 2013
Failed to retrieve data for year 2014
Failed to retrieve data for year 2015
Failed to retrieve data for year 2016
Failed to retrieve data for year 2017
Failed to retrieve data for year 2018
Processing data for year 2019
Saved parquet for year 2019
Processing data for year 2020
Saved parquet for year 2020
Processing data for year 2021
Saved parquet for year 2021
Processing data for year 2022
Saved parquet for year 2022
Processing data for year 2023
Saved parquet for year 2023
Processing data for year 2024
Saved parquet for year 2024
Processing data for year 2025
Saved parquet for year 2025

In [15]:
df_chugoku_2021 = pl.read_parquet(r"/workspace/src/stg/data_lake/electric_forecast/chugoku/juyo-2021.parquet")
df_chugoku_2021.head()

shape: (5, 3)
┌──────────┬──────┬────────────┐
│ DATE     ┆ TIME ┆ 実績(万kW) │
│ ---      ┆ ---  ┆ ---        │
│ str      ┆ str  ┆ i64        │
╞══════════╪══════╪════════════╡
│ 2021/4/1 ┆ 0:00 ┆ 520        │
│ 2021/4/1 ┆ 1:00 ┆ 529        │
│ 2021/4/1 ┆ 2:00 ┆ 566        │
│ 2021/4/1 ┆ 3:00 ┆ 609        │
│ 2021/4/1 ┆ 4:00 ┆ 622        │
└──────────┴──────┴────────────┘

### Shikoku

In [12]:
SKK_PATH = r"/workspace/src/stg/data_lake/electric_forecast/shikoku"
SKK_URL = "https://www.yonden.co.jp/nw/denkiyoho/csv/"
SKK_YEAR_LIST = [i for i in range(2016,2026)]

In [18]:
for year in SKK_YEAR_LIST:
    file_name = f"juyo_shikoku_{str(year)}.csv"
    url = f"{SKK_URL}/{file_name}"
    time.sleep(np.random.uniform(1, 5))
    response = requests.get(url)
    if response.status_code == 200:
        print(f"Processing data for year {year}")
        df = pl.read_csv(source=url, encoding="cp932", skip_rows=2)
        df.write_parquet(os.path.join(SKK_PATH, f"juyo_shikoku_{str(year)}.parquet"))
        print(f"Saved parquet for year {year}")
    else:
        print(f"Failed to retrieve data for year {year}")
        continue

Processing data for year 2016
Saved parquet for year 2016
Processing data for year 2017
Saved parquet for year 2017
Processing data for year 2018
Saved parquet for year 2018
Processing data for year 2019
Saved parquet for year 2019
Processing data for year 2020
Saved parquet for year 2020
Processing data for year 2021
Saved parquet for year 2021
Processing data for year 2022
Saved parquet for year 2022
Processing data for year 2023
Saved parquet for year 2023
Processing data for year 2024
Saved parquet for year 2024
Processing data for year 2025
Saved parquet for year 2025

### KyuShu

In [2]:
KYS_PATH = r"/workspace/src/stg/data_lake/electric_forecast/kyushu"
KYS_URL = "https://www.kyuden.co.jp/td_power_usages/csv/"
KYS_YEAR_LIST = [i for i in range(2011,2026)]
KYS_MONH_LIST = [i for i in range(1,13)]

In [3]:
for year in KYS_YEAR_LIST:
    for month in KYS_MONH_LIST:
        file_name = f"history{str(year)}{str(month).zfill(2)}.csv"
        url = f"{KYS_URL}/{file_name}"
        time.sleep(np.random.uniform(1, 5))
        response = requests.get(url)
        if response.status_code == 200:
            print(f"Processing data for year {str(year)}/{str(month).zfill(2)}")
            df = pl.read_csv(source=url, encoding="cp932", skip_rows=1)
            df.write_parquet(os.path.join(KYS_PATH, f"history{str(year)}{str(month).zfill(2)}.parquet"))
            print(f"Saved parquet for year {str(year)}/{str(month).zfill(2)}")
        else:
            print(f"Failed to retrieve data for year {str(year)}/{str(month).zfill(2)}")
            continue

Failed to retrieve data for year 2011/01
Failed to retrieve data for year 2011/02
Failed to retrieve data for year 2011/03
Failed to retrieve data for year 2011/04
Failed to retrieve data for year 2011/05
Failed to retrieve data for year 2011/06
Failed to retrieve data for year 2011/07
Failed to retrieve data for year 2011/08
Failed to retrieve data for year 2011/09
Failed to retrieve data for year 2011/10
Processing data for year 2011/11
Saved parquet for year 2011/11
Processing data for year 2011/12
Saved parquet for year 2011/12
Processing data for year 2012/01
Saved parquet for year 2012/01
Processing data for year 2012/02
Saved parquet for year 2012/02
Processing data for year 2012/03
Saved parquet for year 2012/03
Processing data for year 2012/04
Saved parquet for year 2012/04
Processing data for year 2012/05
Saved parquet for year 2012/05
Processing data for year 2012/06
Saved parquet for year 2012/06
Processing data for year 2012/07
Saved parquet for year 2012/07
Processing data for year 2012/08
Saved parquet for year 2012/08
Processing data for year 2012/09
Saved parquet for year 2012/09
Processing data for year 2012/10
Saved parquet for year 2012/10
Processing data for year 2012/11
Saved parquet for year 2012/11
Processing data for year 2012/12
Saved parquet for year 2012/12
Processing data for year 2013/01
Saved parquet for year 2013/01
Processing data for year 2013/02
Saved parquet for year 2013/02
Processing data for year 2013/03
Saved parquet for year 2013/03
Processing data for year 2013/04
Saved parquet for year 2013/04
Processing data for year 2013/05
Saved parquet for year 2013/05
Processing data for year 2013/06
Saved parquet for year 2013/06
Processing data for year 2013/07
Saved parquet for year 2013/07
Processing data for year 2013/08
Saved parquet for year 2013/08
Processing data for year 2013/09
Saved parquet for year 2013/09
Processing data for year 2013/10
Saved parquet for year 2013/10
Processing data for year 2013/11
Saved parquet for year 2013/11
Processing data for year 2013/12
Saved parquet for year 2013/12
Processing data for year 2014/01
Saved parquet for year 2014/01
Processing data for year 2014/02
Saved parquet for year 2014/02
Processing data for year 2014/03
Saved parquet for year 2014/03
Processing data for year 2014/04
Saved parquet for year 2014/04
Processing data for year 2014/05
Saved parquet for year 2014/05
Processing data for year 2014/06
Saved parquet for year 2014/06
Processing data for year 2014/07
Saved parquet for year 2014/07
Processing data for year 2014/08
Saved parquet for year 2014/08
Processing data for year 2014/09
Saved parquet for year 2014/09
Processing data for year 2014/10
Saved parquet for year 2014/10
Processing data for year 2014/11
Saved parquet for year 2014/11
Processing data for year 2014/12
Saved parquet for year 2014/12
Processing data for year 2015/01
Saved parquet for year 2015/01
Processing data for year 2015/02
Saved parquet for year 2015/02
Processing data for year 2015/03
Saved parquet for year 2015/03
Processing data for year 2015/04
Saved parquet for year 2015/04
Processing data for year 2015/05
Saved parquet for year 2015/05
Processing data for year 2015/06
Saved parquet for year 2015/06
Processing data for year 2015/07
Saved parquet for year 2015/07
Processing data for year 2015/08
Saved parquet for year 2015/08
Processing data for year 2015/09
Saved parquet for year 2015/09
Processing data for year 2015/10
Saved parquet for year 2015/10
Processing data for year 2015/11
Saved parquet for year 2015/11
Processing data for year 2015/12
Saved parquet for year 2015/12
Processing data for year 2016/01
Saved parquet for year 2016/01
Processing data for year 2016/02
Saved parquet for year 2016/02
Processing data for year 2016/03
Saved parquet for year 2016/03
Processing data for year 2016/04
Saved parquet for year 2016/04
Processing data for year 2016/05
Saved parquet for year 2016/05
Processing data for year 2016/06
Saved parquet for year 2016/06
Processing data for year 2016/07
Saved parquet for year 2016/07
Processing data for year 2016/08
Saved parquet for year 2016/08
Processing data for year 2016/09
Saved parquet for year 2016/09
Processing data for year 2016/10
Saved parquet for year 2016/10
Processing data for year 2016/11
Saved parquet for year 2016/11
Processing data for year 2016/12
Saved parquet for year 2016/12
Processing data for year 2017/01
Saved parquet for year 2017/01
Processing data for year 2017/02
Saved parquet for year 2017/02
Processing data for year 2017/03
Saved parquet for year 2017/03
Processing data for year 2017/04
Saved parquet for year 2017/04
Processing data for year 2017/05
Saved parquet for year 2017/05
Processing data for year 2017/06
Saved parquet for year 2017/06
Processing data for year 2017/07
Saved parquet for year 2017/07
Processing data for year 2017/08
Saved parquet for year 2017/08
Processing data for year 2017/09
Saved parquet for year 2017/09
Processing data for year 2017/10
Saved parquet for year 2017/10
Processing data for year 2017/11
Saved parquet for year 2017/11
Processing data for year 2017/12
Saved parquet for year 2017/12
Processing data for year 2018/01
Saved parquet for year 2018/01
Processing data for year 2018/02
Saved parquet for year 2018/02
Processing data for year 2018/03
Saved parquet for year 2018/03
Processing data for year 2018/04
Saved parquet for year 2018/04
Processing data for year 2018/05
Saved parquet for year 2018/05
Processing data for year 2018/06
Saved parquet for year 2018/06
Processing data for year 2018/07
Saved parquet for year 2018/07
Processing data for year 2018/08
Saved parquet for year 2018/08
Processing data for year 2018/09
Saved parquet for year 2018/09
Processing data for year 2018/10
Saved parquet for year 2018/10
Processing data for year 2018/11
Saved parquet for year 2018/11
Processing data for year 2018/12
Saved parquet for year 2018/12
Processing data for year 2019/01
Saved parquet for year 2019/01
Processing data for year 2019/02
Saved parquet for year 2019/02
Processing data for year 2019/03
Saved parquet for year 2019/03
Processing data for year 2019/04
Saved parquet for year 2019/04
Processing data for year 2019/05
Saved parquet for year 2019/05
Processing data for year 2019/06
Saved parquet for year 2019/06
Processing data for year 2019/07
Saved parquet for year 2019/07
Processing data for year 2019/08
Saved parquet for year 2019/08
Processing data for year 2019/09
Saved parquet for year 2019/09
Processing data for year 2019/10
Saved parquet for year 2019/10
Processing data for year 2019/11
Saved parquet for year 2019/11
Processing data for year 2019/12
Saved parquet for year 2019/12
Processing data for year 2020/01
Saved parquet for year 2020/01
Processing data for year 2020/02
Saved parquet for year 2020/02
Processing data for year 2020/03
Saved parquet for year 2020/03
Processing data for year 2020/04
Saved parquet for year 2020/04
Processing data for year 2020/05
Saved parquet for year 2020/05
Processing data for year 2020/06
Saved parquet for year 2020/06
Processing data for year 2020/07
Saved parquet for year 2020/07
Processing data for year 2020/08
Saved parquet for year 2020/08
Processing data for year 2020/09
Saved parquet for year 2020/09
Processing data for year 2020/10
Saved parquet for year 2020/10
Processing data for year 2020/11
Saved parquet for year 2020/11
Processing data for year 2020/12
Saved parquet for year 2020/12
Processing data for year 2021/01
Saved parquet for year 2021/01
Processing data for year 2021/02
Saved parquet for year 2021/02
Processing data for year 2021/03
Saved parquet for year 2021/03
Processing data for year 2021/04
Saved parquet for year 2021/04
Processing data for year 2021/05
Saved parquet for year 2021/05
Processing data for year 2021/06
Saved parquet for year 2021/06
Processing data for year 2021/07
Saved parquet for year 2021/07
Processing data for year 2021/08
Saved parquet for year 2021/08
Processing data for year 2021/09
Saved parquet for year 2021/09
Processing data for year 2021/10
Saved parquet for year 2021/10
Processing data for year 2021/11
Saved parquet for year 2021/11
Processing data for year 2021/12
Saved parquet for year 2021/12
Processing data for year 2022/01
Saved parquet for year 2022/01
Processing data for year 2022/02
Saved parquet for year 2022/02
Processing data for year 2022/03
Saved parquet for year 2022/03
Processing data for year 2022/04
Saved parquet for year 2022/04
Processing data for year 2022/05
Saved parquet for year 2022/05
Processing data for year 2022/06
Saved parquet for year 2022/06
Processing data for year 2022/07
Saved parquet for year 2022/07
Processing data for year 2022/08
Saved parquet for year 2022/08
Processing data for year 2022/09
Saved parquet for year 2022/09
Processing data for year 2022/10
Saved parquet for year 2022/10
Processing data for year 2022/11
Saved parquet for year 2022/11
Processing data for year 2022/12
Saved parquet for year 2022/12
Processing data for year 2023/01
Saved parquet for year 2023/01
Processing data for year 2023/02
Saved parquet for year 2023/02
Processing data for year 2023/03
Saved parquet for year 2023/03
Processing data for year 2023/04
Saved parquet for year 2023/04
Processing data for year 2023/05
Saved parquet for year 2023/05
Processing data for year 2023/06
Saved parquet for year 2023/06
Processing data for year 2023/07
Saved parquet for year 2023/07
Processing data for year 2023/08
Saved parquet for year 2023/08
Processing data for year 2023/09
Saved parquet for year 2023/09
Processing data for year 2023/10
Saved parquet for year 2023/10
Processing data for year 2023/11
Saved parquet for year 2023/11
Processing data for year 2023/12
Saved parquet for year 2023/12
Processing data for year 2024/01
Saved parquet for year 2024/01
Processing data for year 2024/02
Saved parquet for year 2024/02
Processing data for year 2024/03
Saved parquet for year 2024/03
Processing data for year 2024/04
Saved parquet for year 2024/04
Processing data for year 2024/05
Saved parquet for year 2024/05
Processing data for year 2024/06
Saved parquet for year 2024/06
Processing data for year 2024/07
Saved parquet for year 2024/07
Processing data for year 2024/08
Saved parquet for year 2024/08
Processing data for year 2024/09
Saved parquet for year 2024/09
Processing data for year 2024/10
Saved parquet for year 2024/10
Processing data for year 2024/11
Saved parquet for year 2024/11
Processing data for year 2024/12
Saved parquet for year 2024/12
Processing data for year 2025/01
Saved parquet for year 2025/01
Processing data for year 2025/02
Saved parquet for year 2025/02
Processing data for year 2025/03
Saved parquet for year 2025/03
Processing data for year 2025/04
Saved parquet for year 2025/04
Processing data for year 2025/05
Saved parquet for year 2025/05
Processing data for year 2025/06
Saved parquet for year 2025/06
Processing data for year 2025/07
Saved parquet for year 2025/07
Processing data for year 2025/08
Saved parquet for year 2025/08
Processing data for year 2025/09
Saved parquet for year 2025/09
Processing data for year 2025/10
Saved parquet for year 2025/10
Processing data for year 2025/11
Saved parquet for year 2025/11
Processing data for year 2025/12
Saved parquet for year 2025/12

### okinawa・hokuriku

In [2]:
start = pl.date(year=2016,month=4,day=1)
end   = pl.date(year=2025,month=12,day=13)

DATE_RANGE = pl.DataFrame({"date": pl.select(pl.date_range(start=start, end=end, interval="1d").alias("date"))}).to_series().to_list()

In [3]:
OKW_PATH = r"/workspace/src/stg/data_lake/electric_forecast/okinawa"
HKR_PATH = r"/workspace/src/stg/data_lake/electric_forecast/hokuriku"
OKW_URL = "https://www.okiden.co.jp/denki2/"
HKR_URL = "https://www.rikuden.co.jp/nw/denki-yoho/csv/juyo_05_20200401.csv"

In [13]:
for t_date in DATE_RANGE:
    date_str = t_date.strftime("%Y%m%d")
    okinawa_url = f"{OKW_URL}/juyo_10_{date_str}.csv"
    time.sleep(np.random.uniform(1, 5))
    res_okinawa = requests.get(okinawa_url)
    print(f"Okinawa : {date_str} SAVE")
    with open(os.path.join(OKW_PATH, f"juyo_10_{date_str}.csv"), 'wb') as f:
        f.write(res_okinawa.content)
    if t_date >= date(2020,4,1):
        hokuriku_url = f"{HKR_URL.replace('20200401', date_str)}"
        time.sleep(np.random.uniform(1, 5))
        res_hokuriku = requests.get(hokuriku_url)
        print(f"Hokuriku : {date_str} SAVE")
        with open(os.path.join(HKR_PATH, f"juyo_05_{date_str}.csv"), 'wb') as f:
            f.write(res_okinawa.content)
    else:
        continue

Okinawa : 20160401 SAVE
Okinawa : 20160402 SAVE
Okinawa : 20160403 SAVE
Okinawa : 20160404 SAVE
Okinawa : 20160405 SAVE
Okinawa : 20160406 SAVE
Okinawa : 20160407 SAVE
Okinawa : 20160408 SAVE
Okinawa : 20160409 SAVE
Okinawa : 20160410 SAVE
Okinawa : 20160411 SAVE
Okinawa : 20160412 SAVE
Okinawa : 20160413 SAVE
Okinawa : 20160414 SAVE
Okinawa : 20160415 SAVE
Okinawa : 20160416 SAVE
Okinawa : 20160417 SAVE
Okinawa : 20160418 SAVE
Okinawa : 20160419 SAVE
Okinawa : 20160420 SAVE
Okinawa : 20160421 SAVE
Okinawa : 20160422 SAVE
Okinawa : 20160423 SAVE
Okinawa : 20160424 SAVE
Okinawa : 20160425 SAVE
Okinawa : 20160426 SAVE
Okinawa : 20160427 SAVE
Okinawa : 20160428 SAVE
Okinawa : 20160429 SAVE
Okinawa : 20160430 SAVE
Okinawa : 20160501 SAVE
Okinawa : 20160502 SAVE
Okinawa : 20160503 SAVE
Okinawa : 20160504 SAVE
Okinawa : 20160505 SAVE
Okinawa : 20160506 SAVE
Okinawa : 20160507 SAVE
Okinawa : 20160508 SAVE
Okinawa : 20160509 SAVE
Okinawa : 20160510 SAVE
Okinawa : 20160511 SAVE
Okinawa : 20160512 SAVE
Okinawa : 20160513 SAVE
Okinawa : 20160514 SAVE
Okinawa : 20160515 SAVE
Okinawa : 20160516 SAVE
Okinawa : 20160517 SAVE
Okinawa : 20160518 SAVE
Okinawa : 20160519 SAVE
Okinawa : 20160520 SAVE
Okinawa : 20160521 SAVE
Okinawa : 20160522 SAVE
Okinawa : 20160523 SAVE
Okinawa : 20160524 SAVE
Okinawa : 20160525 SAVE
Okinawa : 20160526 SAVE
Okinawa : 20160527 SAVE
Okinawa : 20160528 SAVE
Okinawa : 20160529 SAVE
Okinawa : 20160530 SAVE
Okinawa : 20160531 SAVE
Okinawa : 20160601 SAVE
Okinawa : 20160602 SAVE
Okinawa : 20160603 SAVE
Okinawa : 20160604 SAVE
Okinawa : 20160605 SAVE
Okinawa : 20160606 SAVE
Okinawa : 20160607 SAVE
Okinawa : 20160608 SAVE
Okinawa : 20160609 SAVE
Okinawa : 20160610 SAVE
Okinawa : 20160611 SAVE
Okinawa : 20160612 SAVE
Okinawa : 20160613 SAVE
Okinawa : 20160614 SAVE
Okinawa : 20160615 SAVE
Okinawa : 20160616 SAVE
Okinawa : 20160617 SAVE
Okinawa : 20160618 SAVE
Okinawa : 20160619 SAVE
Okinawa : 20160620 SAVE
Okinawa : 20160621 SAVE
Okinawa : 20160622 SAVE
Okinawa : 20160623 SAVE
Okinawa : 20160624 SAVE
Okinawa : 20160625 SAVE
Okinawa : 20160626 SAVE
Okinawa : 20160627 SAVE
Okinawa : 20160628 SAVE
Okinawa : 20160629 SAVE
Okinawa : 20160630 SAVE
Okinawa : 20160701 SAVE
Okinawa : 20160702 SAVE
Okinawa : 20160703 SAVE
Okinawa : 20160704 SAVE
Okinawa : 20160705 SAVE
Okinawa : 20160706 SAVE
Okinawa : 20160707 SAVE
Okinawa : 20160708 SAVE
Okinawa : 20160709 SAVE
Okinawa : 20160710 SAVE
Okinawa : 20160711 SAVE
Okinawa : 20160712 SAVE
Okinawa : 20160713 SAVE
Okinawa : 20160714 SAVE
Okinawa : 20160715 SAVE
Okinawa : 20160716 SAVE
Okinawa : 20160717 SAVE
Okinawa : 20160718 SAVE
Okinawa : 20160719 SAVE
Okinawa : 20160720 SAVE
Okinawa : 20160721 SAVE
Okinawa : 20160722 SAVE
Okinawa : 20160723 SAVE
Okinawa : 20160724 SAVE
Okinawa : 20160725 SAVE
Okinawa : 20160726 SAVE
Okinawa : 20160727 SAVE
Okinawa : 20160728 SAVE
Okinawa : 20160729 SAVE
Okinawa : 20160730 SAVE
Okinawa : 20160731 SAVE
Okinawa : 20160801 SAVE
Okinawa : 20160802 SAVE
Okinawa : 20160803 SAVE
Okinawa : 20160804 SAVE
Okinawa : 20160805 SAVE
Okinawa : 20160806 SAVE
Okinawa : 20160807 SAVE
Okinawa : 20160808 SAVE
Okinawa : 20160809 SAVE
Okinawa : 20160810 SAVE
Okinawa : 20160811 SAVE
Okinawa : 20160812 SAVE
Okinawa : 20160813 SAVE
Okinawa : 20160814 SAVE
Okinawa : 20160815 SAVE
Okinawa : 20160816 SAVE
Okinawa : 20160817 SAVE
Okinawa : 20160818 SAVE
Okinawa : 20160819 SAVE
Okinawa : 20160820 SAVE
Okinawa : 20160821 SAVE
Okinawa : 20160822 SAVE
Okinawa : 20160823 SAVE
Okinawa : 20160824 SAVE
Okinawa : 20160825 SAVE
Okinawa : 20160826 SAVE
Okinawa : 20160827 SAVE
Okinawa : 20160828 SAVE
Okinawa : 20160829 SAVE
Okinawa : 20160830 SAVE
Okinawa : 20160831 SAVE
Okinawa : 20160901 SAVE
Okinawa : 20160902 SAVE
Okinawa : 20160903 SAVE
Okinawa : 20160904 SAVE
Okinawa : 20160905 SAVE
Okinawa : 20160906 SAVE
Okinawa : 20160907 SAVE
Okinawa : 20160908 SAVE
Okinawa : 20160909 SAVE
Okinawa : 20160910 SAVE
Okinawa : 20160911 SAVE
Okinawa : 20160912 SAVE
Okinawa : 20160913 SAVE
Okinawa : 20160914 SAVE
Okinawa : 20160915 SAVE
Okinawa : 20160916 SAVE
Okinawa : 20160917 SAVE
Okinawa : 20160918 SAVE
Okinawa : 20160919 SAVE
Okinawa : 20160920 SAVE
Okinawa : 20160921 SAVE
Okinawa : 20160922 SAVE
Okinawa : 20160923 SAVE
Okinawa : 20160924 SAVE
Okinawa : 20160925 SAVE
Okinawa : 20160926 SAVE
Okinawa : 20160927 SAVE
Okinawa : 20160928 SAVE
Okinawa : 20160929 SAVE
Okinawa : 20160930 SAVE
Okinawa : 20161001 SAVE
Okinawa : 20161002 SAVE
Okinawa : 20161003 SAVE
Okinawa : 20161004 SAVE
Okinawa : 20161005 SAVE
Okinawa : 20161006 SAVE
Okinawa : 20161007 SAVE
Okinawa : 20161008 SAVE
Okinawa : 20161009 SAVE
Okinawa : 20161010 SAVE
Okinawa : 20161011 SAVE
Okinawa : 20161012 SAVE
Okinawa : 20161013 SAVE
Okinawa : 20161014 SAVE
Okinawa : 20161015 SAVE
Okinawa : 20161016 SAVE
Okinawa : 20161017 SAVE
Okinawa : 20161018 SAVE
Okinawa : 20161019 SAVE
Okinawa : 20161020 SAVE
Okinawa : 20161021 SAVE
Okinawa : 20161022 SAVE
Okinawa : 20161023 SAVE
Okinawa : 20161024 SAVE
Okinawa : 20161025 SAVE
Okinawa : 20161026 SAVE
Okinawa : 20161027 SAVE
Okinawa : 20161028 SAVE
Okinawa : 20161029 SAVE
Okinawa : 20161030 SAVE
Okinawa : 20161031 SAVE
Okinawa : 20161101 SAVE
Okinawa : 20161102 SAVE
Okinawa : 20161103 SAVE
Okinawa : 20161104 SAVE
Okinawa : 20161105 SAVE
Okinawa : 20161106 SAVE
Okinawa : 20161107 SAVE
Okinawa : 20161108 SAVE
Okinawa : 20161109 SAVE
Okinawa : 20161110 SAVE
Okinawa : 20161111 SAVE
Okinawa : 20161112 SAVE
Okinawa : 20161113 SAVE
Okinawa : 20161114 SAVE
Okinawa : 20161115 SAVE
Okinawa : 20161116 SAVE
Okinawa : 20161117 SAVE
Okinawa : 20161118 SAVE
Okinawa : 20161119 SAVE
Okinawa : 20161120 SAVE
Okinawa : 20161121 SAVE
Okinawa : 20161122 SAVE
Okinawa : 20161123 SAVE
Okinawa : 20161124 SAVE
Okinawa : 20161125 SAVE
Okinawa : 20161126 SAVE
Okinawa : 20161127 SAVE
Okinawa : 20161128 SAVE
Okinawa : 20161129 SAVE
Okinawa : 20161130 SAVE
Okinawa : 20161201 SAVE
Okinawa : 20161202 SAVE
Okinawa : 20161203 SAVE
Okinawa : 20161204 SAVE
Okinawa : 20161205 SAVE
Okinawa : 20161206 SAVE
Okinawa : 20161207 SAVE
Okinawa : 20161208 SAVE
Okinawa : 20161209 SAVE
Okinawa : 20161210 SAVE
Okinawa : 20161211 SAVE
Okinawa : 20161212 SAVE
Okinawa : 20161213 SAVE
Okinawa : 20161214 SAVE
Okinawa : 20161215 SAVE
Okinawa : 20161216 SAVE
Okinawa : 20161217 SAVE
Okinawa : 20161218 SAVE
Okinawa : 20161219 SAVE
Okinawa : 20161220 SAVE
Okinawa : 20161221 SAVE
Okinawa : 20161222 SAVE
Okinawa : 20161223 SAVE
Okinawa : 20161224 SAVE
Okinawa : 20161225 SAVE
Okinawa : 20161226 SAVE
Okinawa : 20161227 SAVE
Okinawa : 20161228 SAVE
Okinawa : 20161229 SAVE
Okinawa : 20161230 SAVE
Okinawa : 20161231 SAVE
Okinawa : 20170101 SAVE
Okinawa : 20170102 SAVE
Okinawa : 20170103 SAVE
Okinawa : 20170104 SAVE
Okinawa : 20170105 SAVE
Okinawa : 20170106 SAVE
Okinawa : 20170107 SAVE
Okinawa : 20170108 SAVE
Okinawa : 20170109 SAVE
Okinawa : 20170110 SAVE
Okinawa : 20170111 SAVE
Okinawa : 20170112 SAVE
Okinawa : 20170113 SAVE
Okinawa : 20170114 SAVE
Okinawa : 20170115 SAVE
Okinawa : 20170116 SAVE
Okinawa : 20170117 SAVE
Okinawa : 20170118 SAVE
Okinawa : 20170119 SAVE
Okinawa : 20170120 SAVE
Okinawa : 20170121 SAVE
Okinawa : 20170122 SAVE
Okinawa : 20170123 SAVE
Okinawa : 20170124 SAVE
Okinawa : 20170125 SAVE
Okinawa : 20170126 SAVE
Okinawa : 20170127 SAVE
Okinawa : 20170128 SAVE
Okinawa : 20170129 SAVE
Okinawa : 20170130 SAVE
Okinawa : 20170131 SAVE
Okinawa : 20170201 SAVE
Okinawa : 20170202 SAVE
Okinawa : 20170203 SAVE
Okinawa : 20170204 SAVE
Okinawa : 20170205 SAVE
Okinawa : 20170206 SAVE
Okinawa : 20170207 SAVE
Okinawa : 20170208 SAVE
Okinawa : 20170209 SAVE
Okinawa : 20170210 SAVE
Okinawa : 20170211 SAVE
Okinawa : 20170212 SAVE
Okinawa : 20170213 SAVE
Okinawa : 20170214 SAVE
Okinawa : 20170215 SAVE
Okinawa : 20170216 SAVE
Okinawa : 20170217 SAVE
Okinawa : 20170218 SAVE
Okinawa : 20170219 SAVE
Okinawa : 20170220 SAVE
Okinawa : 20170221 SAVE
Okinawa : 20170222 SAVE
Okinawa : 20170223 SAVE
Okinawa : 20170224 SAVE
Okinawa : 20170225 SAVE
Okinawa : 20170226 SAVE
Okinawa : 20170227 SAVE
Okinawa : 20170228 SAVE
Okinawa : 20170301 SAVE
Okinawa : 20170302 SAVE
Okinawa : 20170303 SAVE
Okinawa : 20170304 SAVE
Okinawa : 20170305 SAVE
Okinawa : 20170306 SAVE
Okinawa : 20170307 SAVE
Okinawa : 20170308 SAVE
Okinawa : 20170309 SAVE
Okinawa : 20170310 SAVE
Okinawa : 20170311 SAVE
Okinawa : 20170312 SAVE
Okinawa : 20170313 SAVE
Okinawa : 20170314 SAVE
Okinawa : 20170315 SAVE
Okinawa : 20170316 SAVE
Okinawa : 20170317 SAVE
Okinawa : 20170318 SAVE
Okinawa : 20170319 SAVE
Okinawa : 20170320 SAVE
Okinawa : 20170321 SAVE
Okinawa : 20170322 SAVE
Okinawa : 20170323 SAVE
Okinawa : 20170324 SAVE
Okinawa : 20170325 SAVE
Okinawa : 20170326 SAVE
Okinawa : 20170327 SAVE
Okinawa : 20170328 SAVE
Okinawa : 20170329 SAVE
Okinawa : 20170330 SAVE
Okinawa : 20170331 SAVE
Okinawa : 20170401 SAVE
Okinawa : 20170402 SAVE
Okinawa : 20170403 SAVE
Okinawa : 20170404 SAVE
Okinawa : 20170405 SAVE
Okinawa : 20170406 SAVE
Okinawa : 20170407 SAVE
Okinawa : 20170408 SAVE
Okinawa : 20170409 SAVE
Okinawa : 20170410 SAVE
Okinawa : 20170411 SAVE
Okinawa : 20170412 SAVE
Okinawa : 20170413 SAVE
Okinawa : 20170414 SAVE
Okinawa : 20170415 SAVE
Okinawa : 20170416 SAVE
Okinawa : 20170417 SAVE
Okinawa : 20170418 SAVE
Okinawa : 20170419 SAVE
Okinawa : 20170420 SAVE
Okinawa : 20170421 SAVE
Okinawa : 20170422 SAVE
Okinawa : 20170423 SAVE
Okinawa : 20170424 SAVE
Okinawa : 20170425 SAVE
Okinawa : 20170426 SAVE
Okinawa : 20170427 SAVE
Okinawa : 20170428 SAVE
Okinawa : 20170429 SAVE
Okinawa : 20170430 SAVE
Okinawa : 20170501 SAVE
Okinawa : 20170502 SAVE
Okinawa : 20170503 SAVE
Okinawa : 20170504 SAVE
Okinawa : 20170505 SAVE
Okinawa : 20170506 SAVE
Okinawa : 20170507 SAVE
Okinawa : 20170508 SAVE
Okinawa : 20170509 SAVE
Okinawa : 20170510 SAVE
Okinawa : 20170511 SAVE
Okinawa : 20170512 SAVE
Okinawa : 20170513 SAVE
Okinawa : 20170514 SAVE
Okinawa : 20170515 SAVE
Okinawa : 20170516 SAVE
Okinawa : 20170517 SAVE
Okinawa : 20170518 SAVE
Okinawa : 20170519 SAVE
Okinawa : 20170520 SAVE
Okinawa : 20170521 SAVE
Okinawa : 20170522 SAVE
Okinawa : 20170523 SAVE
Okinawa : 20170524 SAVE
Okinawa : 20170525 SAVE
Okinawa : 20170526 SAVE
Okinawa : 20170527 SAVE
Okinawa : 20170528 SAVE
Okinawa : 20170529 SAVE
Okinawa : 20170530 SAVE
Okinawa : 20170531 SAVE
Okinawa : 20170601 SAVE
Okinawa : 20170602 SAVE
Okinawa : 20170603 SAVE
Okinawa : 20170604 SAVE
Okinawa : 20170605 SAVE
Okinawa : 20170606 SAVE
Okinawa : 20170607 SAVE
Okinawa : 20170608 SAVE
Okinawa : 20170609 SAVE
Okinawa : 20170610 SAVE
Okinawa : 20170611 SAVE
Okinawa : 20170612 SAVE
Okinawa : 20170613 SAVE
Okinawa : 20170614 SAVE
Okinawa : 20170615 SAVE
Okinawa : 20170616 SAVE
Okinawa : 20170617 SAVE
Okinawa : 20170618 SAVE
Okinawa : 20170619 SAVE
Okinawa : 20170620 SAVE
Okinawa : 20170621 SAVE
Okinawa : 20170622 SAVE
Okinawa : 20170623 SAVE
Okinawa : 20170624 SAVE
Okinawa : 20170625 SAVE
Okinawa : 20170626 SAVE
Okinawa : 20170627 SAVE
Okinawa : 20170628 SAVE
Okinawa : 20170629 SAVE
Okinawa : 20170630 SAVE
Okinawa : 20170701 SAVE
Okinawa : 20170702 SAVE
Okinawa : 20170703 SAVE
Okinawa : 20170704 SAVE
Okinawa : 20170705 SAVE
Okinawa : 20170706 SAVE
Okinawa : 20170707 SAVE
Okinawa : 20170708 SAVE
Okinawa : 20170709 SAVE
Okinawa : 20170710 SAVE
Okinawa : 20170711 SAVE
Okinawa : 20170712 SAVE
Okinawa : 20170713 SAVE
Okinawa : 20170714 SAVE
Okinawa : 20170715 SAVE
Okinawa : 20170716 SAVE
Okinawa : 20170717 SAVE
Okinawa : 20170718 SAVE
Okinawa : 20170719 SAVE
Okinawa : 20170720 SAVE
Okinawa : 20170721 SAVE
Okinawa : 20170722 SAVE
Okinawa : 20170723 SAVE
Okinawa : 20170724 SAVE
Okinawa : 20170725 SAVE
Okinawa : 20170726 SAVE
Okinawa : 20170727 SAVE
Okinawa : 20170728 SAVE
Okinawa : 20170729 SAVE
Okinawa : 20170730 SAVE
Okinawa : 20170731 SAVE
Okinawa : 20170801 SAVE
Okinawa : 20170802 SAVE
Okinawa : 20170803 SAVE
Okinawa : 20170804 SAVE
Okinawa : 20170805 SAVE
Okinawa : 20170806 SAVE
Okinawa : 20170807 SAVE
Okinawa : 20170808 SAVE
Okinawa : 20170809 SAVE
Okinawa : 20170810 SAVE
Okinawa : 20170811 SAVE
Okinawa : 20170812 SAVE
Okinawa : 20170813 SAVE
Okinawa : 20170814 SAVE
Okinawa : 20170815 SAVE
Okinawa : 20170816 SAVE
Okinawa : 20170817 SAVE
Okinawa : 20170818 SAVE
Okinawa : 20170819 SAVE
Okinawa : 20170820 SAVE
Okinawa : 20170821 SAVE
Okinawa : 20170822 SAVE
Okinawa : 20170823 SAVE
Okinawa : 20170824 SAVE
Okinawa : 20170825 SAVE
Okinawa : 20170826 SAVE
Okinawa : 20170827 SAVE
Okinawa : 20170828 SAVE
Okinawa : 20170829 SAVE
Okinawa : 20170830 SAVE
Okinawa : 20170831 SAVE
Okinawa : 20170901 SAVE
Okinawa : 20170902 SAVE
Okinawa : 20170903 SAVE
Okinawa : 20170904 SAVE
Okinawa : 20170905 SAVE
Okinawa : 20170906 SAVE
Okinawa : 20170907 SAVE
Okinawa : 20170908 SAVE
Okinawa : 20170909 SAVE
Okinawa : 20170910 SAVE
Okinawa : 20170911 SAVE
Okinawa : 20170912 SAVE
Okinawa : 20170913 SAVE
Okinawa : 20170914 SAVE
Okinawa : 20170915 SAVE
Okinawa : 20170916 SAVE
Okinawa : 20170917 SAVE
Okinawa : 20170918 SAVE
Okinawa : 20170919 SAVE
Okinawa : 20170920 SAVE
Okinawa : 20170921 SAVE
Okinawa : 20170922 SAVE
Okinawa : 20170923 SAVE
Okinawa : 20170924 SAVE
Okinawa : 20170925 SAVE
Okinawa : 20170926 SAVE
Okinawa : 20170927 SAVE
Okinawa : 20170928 SAVE
Okinawa : 20170929 SAVE
Okinawa : 20170930 SAVE
Okinawa : 20171001 SAVE
Okinawa : 20171002 SAVE
Okinawa : 20171003 SAVE
Okinawa : 20171004 SAVE
Okinawa : 20171005 SAVE
Okinawa : 20171006 SAVE
Okinawa : 20171007 SAVE
Okinawa : 20171008 SAVE
Okinawa : 20171009 SAVE
Okinawa : 20171010 SAVE
Okinawa : 20171011 SAVE
Okinawa : 20171012 SAVE
Okinawa : 20171013 SAVE
Okinawa : 20171014 SAVE
Okinawa : 20171015 SAVE
Okinawa : 20171016 SAVE
Okinawa : 20171017 SAVE
Okinawa : 20171018 SAVE
Okinawa : 20171019 SAVE
Okinawa : 20171020 SAVE
Okinawa : 20171021 SAVE
Okinawa : 20171022 SAVE
Okinawa : 20171023 SAVE
Okinawa : 20171024 SAVE
Okinawa : 20171025 SAVE
Okinawa : 20171026 SAVE
Okinawa : 20171027 SAVE
Okinawa : 20171028 SAVE
Okinawa : 20171029 SAVE
Okinawa : 20171030 SAVE
Okinawa : 20171031 SAVE
Okinawa : 20171101 SAVE
Okinawa : 20171102 SAVE
Okinawa : 20171103 SAVE
Okinawa : 20171104 SAVE
Okinawa : 20171105 SAVE
Okinawa : 20171106 SAVE
Okinawa : 20171107 SAVE
Okinawa : 20171108 SAVE
Okinawa : 20171109 SAVE
Okinawa : 20171110 SAVE
Okinawa : 20171111 SAVE
Okinawa : 20171112 SAVE
Okinawa : 20171113 SAVE
Okinawa : 20171114 SAVE
Okinawa : 20171115 SAVE
Okinawa : 20171116 SAVE
Okinawa : 20171117 SAVE
Okinawa : 20171118 SAVE
Okinawa : 20171119 SAVE
Okinawa : 20171120 SAVE
Okinawa : 20171121 SAVE
Okinawa : 20171122 SAVE
Okinawa : 20171123 SAVE
Okinawa : 20171124 SAVE
Okinawa : 20171125 SAVE
Okinawa : 20171126 SAVE
Okinawa : 20171127 SAVE
Okinawa : 20171128 SAVE
Okinawa : 20171129 SAVE
Okinawa : 20171130 SAVE
Okinawa : 20171201 SAVE
Okinawa : 20171202 SAVE
Okinawa : 20171203 SAVE
Okinawa : 20171204 SAVE
Okinawa : 20171205 SAVE
Okinawa : 20171206 SAVE
Okinawa : 20171207 SAVE
Okinawa : 20171208 SAVE
Okinawa : 20171209 SAVE
Okinawa : 20171210 SAVE
Okinawa : 20171211 SAVE
Okinawa : 20171212 SAVE
Okinawa : 20171213 SAVE
Okinawa : 20171214 SAVE
Okinawa : 20171215 SAVE
Okinawa : 20171216 SAVE
Okinawa : 20171217 SAVE
Okinawa : 20171218 SAVE
Okinawa : 20171219 SAVE
Okinawa : 20171220 SAVE
Okinawa : 20171221 SAVE
Okinawa : 20171222 SAVE
Okinawa : 20171223 SAVE
Okinawa : 20171224 SAVE
Okinawa : 20171225 SAVE
Okinawa : 20171226 SAVE
Okinawa : 20171227 SAVE
Okinawa : 20171228 SAVE
Okinawa : 20171229 SAVE
Okinawa : 20171230 SAVE
Okinawa : 20171231 SAVE
Okinawa : 20180101 SAVE
Okinawa : 20180102 SAVE
Okinawa : 20180103 SAVE
Okinawa : 20180104 SAVE
Okinawa : 20180105 SAVE
Okinawa : 20180106 SAVE
Okinawa : 20180107 SAVE
Okinawa : 20180108 SAVE
Okinawa : 20180109 SAVE
Okinawa : 20180110 SAVE
Okinawa : 20180111 SAVE
Okinawa : 20180112 SAVE
Okinawa : 20180113 SAVE
Okinawa : 20180114 SAVE
Okinawa : 20180115 SAVE
Okinawa : 20180116 SAVE
Okinawa : 20180117 SAVE
Okinawa : 20180118 SAVE
Okinawa : 20180119 SAVE
Okinawa : 20180120 SAVE
Okinawa : 20180121 SAVE
Okinawa : 20180122 SAVE
Okinawa : 20180123 SAVE
Okinawa : 20180124 SAVE
Okinawa : 20180125 SAVE
Okinawa : 20180126 SAVE
Okinawa : 20180127 SAVE
Okinawa : 20180128 SAVE
Okinawa : 20180129 SAVE
Okinawa : 20180130 SAVE
Okinawa : 20180131 SAVE
Okinawa : 20180201 SAVE
Okinawa : 20180202 SAVE
Okinawa : 20180203 SAVE
Okinawa : 20180204 SAVE
Okinawa : 20180205 SAVE
Okinawa : 20180206 SAVE
Okinawa : 20180207 SAVE
Okinawa : 20180208 SAVE
Okinawa : 20180209 SAVE
Okinawa : 20180210 SAVE
Okinawa : 20180211 SAVE
Okinawa : 20180212 SAVE
Okinawa : 20180213 SAVE
Okinawa : 20180214 SAVE
Okinawa : 20180215 SAVE
Okinawa : 20180216 SAVE
Okinawa : 20180217 SAVE
Okinawa : 20180218 SAVE
Okinawa : 20180219 SAVE
Okinawa : 20180220 SAVE
Okinawa : 20180221 SAVE
Okinawa : 20180222 SAVE
Okinawa : 20180223 SAVE
Okinawa : 20180224 SAVE
Okinawa : 20180225 SAVE
Okinawa : 20180226 SAVE
Okinawa : 20180227 SAVE
Okinawa : 20180228 SAVE
Okinawa : 20180301 SAVE
Okinawa : 20180302 SAVE
Okinawa : 20180303 SAVE
Okinawa : 20180304 SAVE
Okinawa : 20180305 SAVE
Okinawa : 20180306 SAVE
Okinawa : 20180307 SAVE
Okinawa : 20180308 SAVE
Okinawa : 20180309 SAVE
Okinawa : 20180310 SAVE
Okinawa : 20180311 SAVE
Okinawa : 20180312 SAVE
Okinawa : 20180313 SAVE
Okinawa : 20180314 SAVE
Okinawa : 20180315 SAVE
Okinawa : 20180316 SAVE
Okinawa : 20180317 SAVE
Okinawa : 20180318 SAVE
Okinawa : 20180319 SAVE
Okinawa : 20180320 SAVE
Okinawa : 20180321 SAVE
Okinawa : 20180322 SAVE
Okinawa : 20180323 SAVE
Okinawa : 20180324 SAVE
Okinawa : 20180325 SAVE
Okinawa : 20180326 SAVE
Okinawa : 20180327 SAVE
Okinawa : 20180328 SAVE
Okinawa : 20180329 SAVE
Okinawa : 20180330 SAVE
Okinawa : 20180331 SAVE
Okinawa : 20180401 SAVE
Okinawa : 20180402 SAVE
Okinawa : 20180403 SAVE
Okinawa : 20180404 SAVE
Okinawa : 20180405 SAVE
Okinawa : 20180406 SAVE
Okinawa : 20180407 SAVE
Okinawa : 20180408 SAVE
Okinawa : 20180409 SAVE
Okinawa : 20180410 SAVE
Okinawa : 20180411 SAVE
Okinawa : 20180412 SAVE
Okinawa : 20180413 SAVE
Okinawa : 20180414 SAVE
Okinawa : 20180415 SAVE
Okinawa : 20180416 SAVE
Okinawa : 20180417 SAVE
Okinawa : 20180418 SAVE
Okinawa : 20180419 SAVE
Okinawa : 20180420 SAVE
Okinawa : 20180421 SAVE
Okinawa : 20180422 SAVE
Okinawa : 20180423 SAVE
Okinawa : 20180424 SAVE
Okinawa : 20180425 SAVE
Okinawa : 20180426 SAVE
Okinawa : 20180427 SAVE
Okinawa : 20180428 SAVE
Okinawa : 20180429 SAVE
Okinawa : 20180430 SAVE
Okinawa : 20180501 SAVE
Okinawa : 20180502 SAVE
Okinawa : 20180503 SAVE
Okinawa : 20180504 SAVE
Okinawa : 20180505 SAVE
Okinawa : 20180506 SAVE
Okinawa : 20180507 SAVE
Okinawa : 20180508 SAVE
Okinawa : 20180509 SAVE
Okinawa : 20180510 SAVE
Okinawa : 20180511 SAVE
Okinawa : 20180512 SAVE
Okinawa : 20180513 SAVE
Okinawa : 20180514 SAVE
Okinawa : 20180515 SAVE
Okinawa : 20180516 SAVE
Okinawa : 20180517 SAVE
Okinawa : 20180518 SAVE
Okinawa : 20180519 SAVE
Okinawa : 20180520 SAVE
Okinawa : 20180521 SAVE
Okinawa : 20180522 SAVE
Okinawa : 20180523 SAVE
Okinawa : 20180524 SAVE
Okinawa : 20180525 SAVE
Okinawa : 20180526 SAVE
Okinawa : 20180527 SAVE
Okinawa : 20180528 SAVE
Okinawa : 20180529 SAVE
Okinawa : 20180530 SAVE
Okinawa : 20180531 SAVE
Okinawa : 20180601 SAVE
Okinawa : 20180602 SAVE
Okinawa : 20180603 SAVE
Okinawa : 20180604 SAVE
Okinawa : 20180605 SAVE
Okinawa : 20180606 SAVE
Okinawa : 20180607 SAVE
Okinawa : 20180608 SAVE
Okinawa : 20180609 SAVE
Okinawa : 20180610 SAVE
Okinawa : 20180611 SAVE
Okinawa : 20180612 SAVE
Okinawa : 20180613 SAVE
Okinawa : 20180614 SAVE
Okinawa : 20180615 SAVE
Okinawa : 20180616 SAVE
Okinawa : 20180617 SAVE
Okinawa : 20180618 SAVE
Okinawa : 20180619 SAVE
Okinawa : 20180620 SAVE
Okinawa : 20180621 SAVE
Okinawa : 20180622 SAVE
Okinawa : 20180623 SAVE
Okinawa : 20180624 SAVE
Okinawa : 20180625 SAVE
Okinawa : 20180626 SAVE
Okinawa : 20180627 SAVE
Okinawa : 20180628 SAVE
Okinawa : 20180629 SAVE
Okinawa : 20180630 SAVE
Okinawa : 20180701 SAVE
Okinawa : 20180702 SAVE
Okinawa : 20180703 SAVE
Okinawa : 20180704 SAVE
Okinawa : 20180705 SAVE
Okinawa : 20180706 SAVE
Okinawa : 20180707 SAVE
Okinawa : 20180708 SAVE
Okinawa : 20180709 SAVE
Okinawa : 20180710 SAVE
Okinawa : 20180711 SAVE
Okinawa : 20180712 SAVE